### ISSUE TITLE
How do I contact you?

### ISSUE THREAD

**Issue by shelomito12** [BOT-HAT/Youtube-First-Comment-Bot#1]
Have an email?

**Comment by shelomito12** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hey thanks for replying.I'm looking for some help. I have a headless Linux VPS where I'm running a radio station.I want to get a YouTube notification service that monitors X channels that when they go live, I will program an external Python or Bash script to use that live feed and send only audio to my radio station.Does your application use some kind of notification feature? If not, do you know how to get or write a script for that?Thanks very much in advance!                                                                                                                                             Sent via BlackBerry Hub+                                                                                                                                                                           From: notifications@github.comSent: April 29, 2020 8:10 AMTo: Youtube-First-Comment-Bot@noreply.github.comReply-to: reply@reply.github.comCc: jzvi12@aol.com; author@noreply.github.comSubject: Re: [BOT-HAT/Youtube-First-Comment-Bot] How do I contact you? (#1)  
you just did

**Comment by jzvi12** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hey thanks for the tip. I was a little busy deploying an nginx-rtmp server and other critical tools which are now configured and ready to receive feed in different ways, so now with your help I can finish my idea. Basically, I'm using a nice little tool called streamlink along with ffmpeg which both work together in order to send a YouTube live (HLS) stream to my RTMP (nginx) server. Of course, this only works if I run the specific command manually, so I need to automate it with the help of your Python script.Can you please confirm if your code will be also capable of searching for YouTube live streams?                                                                                                                                             Sent via BlackBerry Hub+                                                                                                                                                                           From: notifications@github.comSent: May 5, 2020 3:25 AMTo: Youtube-First-Comment-Bot@noreply.github.comReply-to: reply@reply.github.comCc: jzvi12@aol.com; author@noreply.github.comSubject: Re: [BOT-HAT/Youtube-First-Comment-Bot] How do I contact you? (#1)  
import httplib2
import os
import sys
import time
from apiclient.discovery import build_from_document
from apiclient.errors import HttpError
from oauth2client.client import flow_from_clientsecrets
from oauth2client.file import Storage
from oauth2client.tools import argparser, run_flow
======== Configure the following variables ===========
#uploads id
cid="UUX6OQ3DkcsbYNE6v8uQQuVA"
#last video id wMuYiLby3-s
lastvid="Z9WQy9uEY8M"
waiting time intervel in seconds
intervel=5
#comment you need to post
comment="Put your text here"
CLIENT_SECRETS_FILE = "./client_secrets.json"
YOUTUBE_READ_WRITE_SSL_SCOPE = "https://www.googleapis.com/auth/youtube.force-ssl"
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"
MISSING_CLIENT_SECRETS_MESSAGE = """
WARNING: Please configure OAuth 2.0
To make this sample run you will need to populate the client_secrets.json file
found at:
%s
with information from the APIs Console
https://console.developers.google.com
For more information about the client_secrets.json file format, please visit:
https://developers.google.com/api-client-library/python/guide/aaa_client_secrets
""" % os.path.abspath(os.path.join(os.path.dirname(file),
CLIENT_SECRETS_FILE))
def get_authenticated_service(args):
flow = flow_from_clientsecrets(CLIENT_SECRETS_FILE, scope=YOUTUBE_READ_WRITE_SSL_SCOPE,
message=MISSING_CLIENT_SECRETS_MESSAGE)
storage = Storage("%s-oauth2.json" % sys.argv[0])
credentials = storage.get()
if credentials is None or credentials.invalid:
credentials = run_flow(flow, storage, args)
with open("youtube-v3-discoverydocument.json", "r") as f:
doc = f.read()
return build_from_document(doc, http=credentials.authorize(httplib2.Http()))
def lastvideo(youtube, cid):
request = youtube.playlistItems().list(
part="snippet",
playlistId=cid
)
response = request.execute()
return(response["items"][0]["snippet"]["resourceId"]["videoId"])
argparser.add_argument("--text", help="Required; text that will be used as comment.")
args = argparser.parse_args()
args.videoid=lastvid
args.text=comment
youtube = get_authenticated_service(args)
i=0
while True:
last=lastvideo(youtube,cid)
i=i+1
if(last!=lastvid):
print(last)
try:
#your code here
lastvid=last

**Comment by jzvi12** [comment]
Hey let me know if the above is possible. Have a nice weekend!

**Comment by shelomito12** [comment]
I used the YouTube API to check if a channel is live. I used the search:list resource of the Data YouTube API to request:
```
https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=INSERTCHANNELID&type=video&eventType=live&key=INSERTAPIKEY
```

Below is a sample response from a channel whose ID is UCkAGrHCLFmlK3H2kd6isipg:
```
{
        "kind": "youtube#searchListResponse",
        "etag": "\"XI7nbFXulYBIpL0ayR_gDh3eu1k/uRiunq1ENxSYb-QSWiTZ-19LMTw\"",
        "regionCode": "KE",
        "pageInfo": {
           "totalResults": 1,
           "resultsPerPage": 5
        },
        "items": [
           {
               "kind": "youtube#searchResult",
               "etag": "\"XI7nbFXulYBIpL0ayR_gDh3eu1k/OdHNP04ScnsmHXJ7yMxYEEt9nzg\"",
               "id": {
                   "kind": "youtube#video",
                   "videoId": "0hQfNwo6ce0"
               },
               "snippet": {
                   "publishedAt": "2018-10-06T05:29:14.000Z",
                   "channelId": "UCkAGrHCLFmlK3H2kd6isipg",
                   "title": "Best of Bean | Live Stream | Mr Bean Official",
                   "description": "Help Mr Bean reach 10 million subscribers! Stay tuned...",
                   "thumbnails": {
                       "default": {
                           "url": "https://i.ytimg.com/vi/0hQfNwo6ce0/default_live.jpg",
                           "width": 120,
                           "height": 90
                       },
                       "medium": {
                           "url": "https://i.ytimg.com/vi/0hQfNwo6ce0/mqdefault_live.jpg",
                           "width": 320,
                           "height": 180
                       },
                       "high": {
                           "url": "https://i.ytimg.com/vi/0hQfNwo6ce0/hqdefault_live.jpg",
                           "width": 480,
                           "height": 360
                       }
                   },
                   "channelTitle": "Mr Bean",
                   "liveBroadcastContent": "live"
               }
           },
           ]
}
```
From the above JSON response, we check the `totalResults` value. The `totalResults` can only be 1 or 0. If that value is 0, we know that we don’t have a live channel. If the value is 1, we will go ahead and check the `videoId` value and do whatever we want with it in the python script.
